[package]
name = "ohm-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
ohm-core.workspace = true

encase.workspace = true
pollster.workspace = true
raw-window-handle.workspace = true
self_cell.workspace = true
slotmap.workspace = true
wgpu.workspace = true
